version: "3"

services:
  test:
    build: .
    container_name: test
    depends_on:
      db:
        condition: service_healthy

  db:
    build: .
    container_name: db
    healthcheck:
      test: ["CMD", "sleep", "5"]
      interval: 1s
      timeout: 10s
      retries: 5
